"""changed user requirements

Revision ID: 4fb174977c59
Revises: 28fe76965328
Create Date: 2024-07-28 20:55:31.438526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fb174977c59'
down_revision = '28fe76965328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('length', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('width', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=False))
        batch_op.drop_column('outer_width')
        batch_op.drop_column('outer_height')
        batch_op.drop_column('outer_length')
        batch_op.drop_column('inner_width')
        batch_op.drop_column('inner_height')
        batch_op.drop_column('inner_length')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_email')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=False))
        batch_op.create_index('ix_user_email', ['email'], unique=1)

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inner_length', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('inner_height', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('inner_width', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('outer_length', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('outer_height', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('outer_width', sa.FLOAT(), nullable=False))
        batch_op.drop_column('height')
        batch_op.drop_column('width')
        batch_op.drop_column('length')

    # ### end Alembic commands ###
